package tiendahibernate.hibernatefiles;
// Generated 04-mar-2018 12:18:25 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comenta generated by hbm2java
 */
public class Comenta  implements java.io.Serializable {


     private Integer id;
     private Articulo articulo;
     private Usuario usuario;
     private Date fecha;
     private String comentario;

    public Comenta() {
    }

    public Comenta(Articulo articulo, Usuario usuario, Date fecha, String comentario) {
       this.articulo = articulo;
       this.usuario = usuario;
       this.fecha = fecha;
       this.comentario = comentario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


