package tiendahibernate.hibernatefiles;
// Generated 04-mar-2018 12:18:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String login;
     private String pass;
     private Set compras = new HashSet(0);
     private Set comentas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String nombre, String login, String pass) {
        this.nombre = nombre;
        this.login = login;
        this.pass = pass;
    }
    public Usuario(String nombre, String login, String pass, Set compras, Set comentas) {
       this.nombre = nombre;
       this.login = login;
       this.pass = pass;
       this.compras = compras;
       this.comentas = comentas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }
    public Set getComentas() {
        return this.comentas;
    }
    
    public void setComentas(Set comentas) {
        this.comentas = comentas;
    }




}


